import os
import json
from ghostcheck.checks.ai_marker import AIMarker
from ghostcheck.scanner import Scanner
from ghostcheck.config import GhostCheckConfig

def test_scan_file_comments():
    scanner = AIMarker()
    content = """
    # This is a human comment
    # Generated by Copilot
    def foo():
        pass
    // Auto-generated by Claude
    -- AI-assisted function
    REM Generated by DeepSeek
    :: Generated by Gemini
    <# Generated by ChatGPT #>
    """
    findings = scanner.scan_file_comments("test.py", content)
    
    names = [f['name'] for f in findings]
    # Check that all comment styles trigger
    assert names.count("ai_comment_signature") == 6
    assert all(f['severity'] == 'INFO' for f in findings)

def test_scan_git_history_mocked(monkeypatch, tmp_path):
    # Mock subprocess.run to return custom commit messages
    class MockCompletedProcess:
        def __init__(self, stdout, returncode=0):
            self.stdout = stdout
            self.returncode = returncode

    def mock_run(args, **kwargs):
        # Commit 1: Unreviewed Claude commit (using \x1f and \x1e delimiters)
        # Commit 2: Reviewed Copilot commit (case-insensitive review trailer)
        # Commit 3: Human commit with @anthropic.com domain (no warning)
        simulated_output = (
            "c1c1c1c1\x1fnoreply@anthropic.com\x1ffeat: add new agent logic\n\n"
            "Co-authored-by: Claude <noreply@anthropic.com>\x1e"
            "c2c2c2c2\x1fcopilot@github.com\x1ffeat: improve prompt handling\n\n"
            "Co-authored-by: Copilot <copilot@github.com>\n"
            "reviewed-by: Human Lead <human@example.com>\x1e"
            "c3c3c3c3\x1fhuman@anthropic.com\x1ffeat: normal human commit\n\n"
            "Co-authored-by: Human Dev <human@anthropic.com>\x1e"
        )
        # We output raw bytes
        return MockCompletedProcess(simulated_output.encode('utf-8'))

    monkeypatch.setattr("subprocess.run", mock_run)
    monkeypatch.setattr("shutil.which", lambda name: "mocked_git")
    
    # Ensure a dummy .git directory exists
    git_dir = tmp_path / ".git"
    git_dir.mkdir(exist_ok=True)
    
    scanner = AIMarker(root_path=str(tmp_path))
    findings = scanner.scan_git_history()
    
    # Only the unreviewed Claude commit (Commit 1) should trigger a warning
    # Commit 2 is reviewed, Commit 3 is by a human dev at Anthropic.
    assert len(findings) == 1
    assert findings[0]['name'] == 'ai_unreviewed_commit'
    assert findings[0]['severity'] == 'MEDIUM'
    assert 'c1c1c1c1' in findings[0]['suggestion']

def test_scanner_end_to_end_integration(tmp_path):
    # Tests that the new plugins are automatically loaded and executed in the main Scanner pipeline
    
    # 1. Create a prompt template file
    prompt_content = "You are a helpful assistant. System instructions: {system}\nSummarize this text: {user_input}"
    prompts_dir = tmp_path / "prompts"
    prompts_dir.mkdir()
    prompt_file = prompts_dir / "summary.prompt"
    prompt_file.write_text(prompt_content)
    
    # 2. Create a source file with AI comment
    source_content = "// Generated by Copilot\ndef calculate():\n    return 42"
    src_dir = tmp_path / "src"
    src_dir.mkdir()
    source_file = src_dir / "utils.py"
    source_file.write_text(source_content)
    
    # Initialize the core scanner config and scanner instance
    config = GhostCheckConfig(str(tmp_path))
    scanner = Scanner(root_path=str(tmp_path), config=config.config)
    
    # Assert both PromptTemplateScanner and AIMarker are instantiated in the scanner list
    loaded_names = [getattr(s, 'name', '') for s in scanner.scanners]
    assert "prompt_template_supplychain_scanner" in loaded_names
    assert "ai_marker_logic_scanner" in loaded_names
    
    # Perform scan on the workspace
    findings = scanner.scan()
    
    # Verify we get the expected findings from our new plugins
    finding_names = [f['name'] for f in findings]
    assert "high_risk_placeholder_name" in finding_names
    assert "missing_input_delimiter" in finding_names
    assert "ai_comment_signature" in finding_names
